## What we have learned in DS 1.1 as a Data Analyst? 

* Learned the principles of effective storytelling

* You begin making proposals and decisions based on analysis

* You Explorated Data Analysis (EDA), you focused on the basics of statistical inference, hypothesis testing, correlation

* Check this out as a good resource for Data Analyst/ Data Engineer/ Data Scientist roles:

https://www.springboard.com/blog/wp-content/uploads/2016/07/UltimateGuidetoDataScienceInterviews-1.pdf

## What we are going to learn in DS 2.1 which covers Machine Learning?

### what is machine learning?

* Use data and algorithm that predict or classify the useen upcoming data with acceptable accuracy

### Two major machine learning algorithm:

1. Supervised Learning

2. Unsupervised Learning

The supevised learning is used to do:

1. Regression --> Temporature prediction, stock market prediction, next purchased item prediction

2. Classification --> Is an email spam or not-spam, is dog in the image or cat, is a comment about a post positive or negative or neutral 

The unspurvised learning is used to do:

1. Cluster data into groups

2. Reduce the dimention of features

## Machine Learning Components:

<img src="Images/machine-learning.png">

## What Level of Math Do We Need for Machine Learning?

I do recommend to refresh or learn the following topics:

1. Calculus

2. Linear Algebra

3. Probability and styatistics

<img src="Images/intro_2.png" width="500">

## DS 1.1 and DS 2.1 Comparison

In DS 1.1, for example when use Titanic dataset, we were interested to explore the data:

1- How many female passenger survived at section C?

In DS 2.1, we are interested in predicting:

1- If we know a passenger was female, young, embarked at section C and her Pclass was 1, predict has she survived or not?

## Data Precrosessing for Machine Learning:

### Scaling, Normalization, One-hot encoding, Label encoding

Please read: https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_quick_guide.htm

Please read: http://scikit-learn.org/stable/modules/preprocessing.html

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html

Also, look at the first page here: https://www.analyticsvidhya.com/infographics/Scikit-Learn-Infographic.pdf

## Activity for DATA Scaling: Max_Min Scaler

## Both options can be used on a dataset it just depends which one works best for the best accuracy possible depending on the data.

## Activity: A two dimensional array (Matrix) X is given, write a function that:

- Subtract the minimum element of each column from all the elements of that column

- Then devide the result to the range of value for each column

Hint: range is the difference between the maximum element and minimum element of each column

In [27]:
import numpy as np

def max_min_s(X):
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

X_train = np.array([[1000.0, 2.0], [1500.0, 3.0]])
print(max_min_s(X_train))
#np.mean(X_train[0])
#np.mean(X_train[::1])

[[0. 0.]
 [1. 1.]]


In [8]:
np.mean(X_train[:,0]) # mean of first column

1250.0

In [9]:
np.mean(X_train[:,1]) # mean of 2nd column

2.5

In [2]:
from sklearn import preprocessing

# When you have multiple columns that differ in range 
min_max_scaler = preprocessing.MinMaxScaler() # scales columns 
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

[[0. 0.]
 [1. 1.]]


In [3]:
import sklearn
print(sklearn.__version__)

0.21.2


## Activity: A two dimensional array (Matrix) X is given, write a function that:

- Subtract the mean element of each column from all the elements of that column

- Then divide the result to the standard deviation of value for each column

In [34]:
def standard_scaler(a):
    col1 = a[:,0]
    col2 = a[:,1]
    col1 = (col1.mean() - col1) // np.std(col1)
    col2 = (col2.mean() - col2) // np.std(col2)
    return np.array([col1, col2])
print(standard_scaler(X_train))
    
    

[[ 1. -1.]
 [ 1. -1.]]


In [31]:
for item in X_train[:,1]:
    print(item)

2.0
3.0


[2. 3.]


In [28]:
X_train = np.array([[1000.0, 2.0], [1500.0, 3.0]])
def standard_s(arr):  
    col2 = (arr[:1]-np.mean(arr[:,1])) // np.std(arr[:,1])#(np.mean(arr[:,0])-arr) // np.std(arr[:0])
    col1 = (arr[:0]-np.mean(arr[:0])) // np.std(arr[:,0])#(np.mean(arr[:,1])-arr) // np.std(arr[:1])
    return np.array([col1,col2])
print(convert(X_train))

[array([], shape=(0, 2), dtype=float64) array([[ 1.995e+03, -1.000e+00]])]


In [10]:
def standard_s(X):
    return (X - X.mean(axis=0)) /X.std(axis=0) # axis=0 == column wise

print(standard_s(X_train))

[[-1. -1.]
 [ 1.  1.]]


In [6]:
standard_scaler = preprocessing.StandardScaler()
X_ss = standard_scaler.fit_transform(X_train)
print(X_ss)

[[-1. -1.]
 [ 1.  1.]]


## Onehot Encoding Churn Modelling Activity 

In [58]:
import pandas as pd
df = pd.read_csv('Datasets/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [59]:
#df['Geography'].unique()
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [60]:
### Define 

In [61]:
# we dont care abt the first three columns(RowNumber, CustomerId, Surname)
# as those don't factorin whether a person churns or not
X = df.iloc[:, 3:13].values

# target column 
#we want to predict the exit value
#which theefore makes it our target column
y = df.iloc[:, 13].values

### print first 10 rows of matrix

In [62]:
print(X[0:10,:])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 'Male' 27 2 134603.88 1 1 1 71725.73]]


## Apply Label Encoder to second and third columns 

In [63]:
from sklearn.preprocessing import LabelEncoder

label_encoder_x_1 = LabelEncoder()
X[:,1] = label_encoder_x_1.fit_transform(X[:,1])
label_encoder_x_2 = LabelEncoder()
X[:,2] = label_encoder_x_2.fit_transform(X[:,2])
print(X[0:10,:])
print(X.shape)

[[619 0 0 42 2 0.0 1 1 1 101348.88]
 [608 2 0 41 1 83807.86 1 0 1 112542.58]
 [502 0 0 42 8 159660.8 3 1 0 113931.57]
 [699 0 0 39 1 0.0 2 0 0 93826.63]
 [850 2 0 43 2 125510.82 1 1 1 79084.1]
 [645 2 1 44 8 113755.78 2 1 0 149756.71]
 [822 0 1 50 7 0.0 2 1 1 10062.8]
 [376 1 0 29 4 115046.74 4 1 0 119346.88]
 [501 0 1 44 4 142051.07 2 0 1 74940.5]
 [684 0 1 27 2 134603.88 1 1 1 71725.73]]
(10000, 10)


### LabelEncoder has replaced France with 0, Germany with 1, and Spain with 2. What else do you notice?

In [68]:
from sklearn.preprocessing import OneHotEncoder


one_hot_encoder = OneHotEncoder(categorical_features=[1,2])
X = one_hot_encoder.fit_transform(X).toarray()
print(pd.DataFrame(X[0:10,:]))

     0    1    2    3    4    5    6    7    8      9    10   11         12  \
0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0  619.0  42.0  2.0       0.00   
1  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  608.0  41.0  1.0   83807.86   
2  1.0  0.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0  502.0  42.0  8.0  159660.80   
3  1.0  0.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0  699.0  39.0  1.0       0.00   
4  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  850.0  43.0  2.0  125510.82   
5  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0  645.0  44.0  8.0  113755.78   
6  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  822.0  50.0  7.0       0.00   
7  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  376.0  29.0  4.0  115046.74   
8  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  501.0  44.0  4.0  142051.07   
9  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  684.0  27.0  2.0  134603.88   

    13   14   15         16  
0  1.0  1.0  1.0  101348.88  
1  1.0  0.0  1.0  112542.58  
2  3.0  1.0  0.0  113931.57  
3  2.0  0.

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


### We can do label encoding and one-hot encoding at the same time in pandas

In [54]:
import pandas as pd

X = df.iloc[:, 3:13]
y = df.iloc[:, 13]
pd.get_dummies(X).head(10)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   
5          645   44       8  113755.78              2          1   
6          822   50       7       0.00              2          1   
7          376   29       4  115046.74              4          1   
8          501   44       4  142051.07              2          0   
9          684   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88                 1                  0   
1               1        112542.58                 0                  0   
2               0        113931.57                 1                  0   
3               0         93826.63                 1                  0   
4               1         79084.10                 0                  0   
5               0        149756.71                 0                  0   
6               1         10062.80                 1                  0   
7               0        119346.88                 0                  1   
8               1         74940.50                 1                  0   
9               1         71725.73                 1                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                1              1            0  
2                0              1            0  
3                0              1            0  
4                1              1            0  
5                1              0            1  
6                0              0            1  
7                0              1            0  
8                0              0            1  
9                0              0            1

In [55]:
pd.get_dummies(X).head(10).values

array([[6.1900000e+02, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [6.0800000e+02, 4.1000000e+01, 1.0000000e+00, 8.3807860e+04,
        1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1254258e+05,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [5.0200000e+02, 4.2000000e+01, 8.0000000e+00, 1.5966080e+05,
        3.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.1393157e+05,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [6.9900000e+02, 3.9000000e+01, 1.0000000e+00, 0.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 0.0000000e+00, 9.3826630e+04,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [8.5000000e+02, 4.3000000e+01, 2.0000000e+00, 1.2551082e+05,
        1.0000000e+0

## The Python package that we use for ML

Sklearn

The OOP paradigm for all Sklearn models: 
https://www.springboard.com/blog/wp-content/uploads/2016/07/UltimateGuidetoDataScienceInterviews-1.pdf

## ML Steps:

1- Data Reading and Cleaning

2- Data Preprocessing

3- Data Splitting

4- Model selection

5- Model Fitting

6- Model Evaluation

## How do we evalue the machine learning models?

For supervised learning it is possible to evaluate the model from train and test data

For regression, the evaluation metrics are:

1. Mean Squared Error (MSE)

2. Mean Absolute Error (MAE)

For classification, the evaluation metrics are:

1. Classification Accuracy

2. Classification Recall, Precision and F1 score


For unsupervised learning there are no systematic approach to evaluate the models but the are ways to do it  